name: Build and Upload bsdl Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build binary
      run: |
        mkdir -p build
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/bsdl-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: bsdl-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/bsdl-${{ matrix.goos }}-${{ matrix.goarch }}
